rootProject.name = 'pulse'

include 'com.zutubi.util'
include 'com.zutubi.i18n'
include 'com.zutubi.validation.annotations'
include 'com.zutubi.validation'
include 'com.zutubi.tove.annotations'
include 'com.zutubi.tove'
include 'com.zutubi.pulse.core'
include 'com.zutubi.pulse.servercore'
include 'com.zutubi.pulse.slave'
