plugins {
    id 'java'
}

group = 'zutubi'
version = '2.7.0-dev'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

sourceSets {
    main {
        java { srcDirs = ['src/java'] }
        resources {
            srcDirs = ['src/java']
            exclude '**/*.java'
        }
    }
    test {
        java { srcDirs = ['src/test'] }
        resources {
            srcDirs = ['src/test']
            exclude '**/*.java'
        }
    }
}

repositories {
    ivy {
        url = uri("${rootProject.projectDir}/repository")
        patternLayout {
            ivy '[organisation]/[module]/ivy-[revision].xml'
            artifact '[organisation]/[module]/jars/[artifact]-[revision].[ext]'
        }
        metadataSources { ivyDescriptor() }
    }
}

dependencies {
    implementation project(':com.zutubi.util')
    implementation 'com.google:com.google.guava:18.0'
    testImplementation project(path: ':com.zutubi.util', configuration: 'testOutput')
    testImplementation 'org.junit:org.junit:4.8.2'
}
